# Generated by Django 4.2.3 on 2023-07-18 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table="'core.post'",
        ),
    ]
